name: exo_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  xml: ^6.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  url_launcher: ^6.2.1
  google_generative_ai: ^0.2.0
  timeago: ^3.7.0
  image_picker: ^1.2.0
  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo-02.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/