// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCqtbaI8ff3x3nAu2tt1fPnc2fb5x4210',
    appId: '1:267129806875:web:301d02b2419942fad218be',
    messagingSenderId: '267129806875',
    projectId: 'exoai-70c21',
    authDomain: 'exoai-70c21.firebaseapp.com',
    storageBucket: 'exoai-70c21.firebasestorage.app',
    measurementId: 'G-R3EHZ1DEJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6UmMS7mlEFlD4U0IHSEXg1-2epOfxwyU',
    appId: '1:267129806875:android:61a75b98423fa214d218be',
    messagingSenderId: '267129806875',
    projectId: 'exoai-70c21',
    storageBucket: 'exoai-70c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ihXyGGIZaRxWf2ZUfD9OyDKBUv2Rk_4',
    appId: '1:267129806875:ios:b7df50f7aa44d56fd218be',
    messagingSenderId: '267129806875',
    projectId: 'exoai-70c21',
    storageBucket: 'exoai-70c21.firebasestorage.app',
    iosBundleId: 'com.example.exoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ihXyGGIZaRxWf2ZUfD9OyDKBUv2Rk_4',
    appId: '1:267129806875:ios:b7df50f7aa44d56fd218be',
    messagingSenderId: '267129806875',
    projectId: 'exoai-70c21',
    storageBucket: 'exoai-70c21.firebasestorage.app',
    iosBundleId: 'com.example.exoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCqtbaI8ff3x3nAu2tt1fPnc2fb5x4210',
    appId: '1:267129806875:web:575f49b070383f10d218be',
    messagingSenderId: '267129806875',
    projectId: 'exoai-70c21',
    authDomain: 'exoai-70c21.firebaseapp.com',
    storageBucket: 'exoai-70c21.firebasestorage.app',
    measurementId: 'G-F5VWNPZZ3J',
  );

}